### ISSUE TITLE
playbooks/byo/config.yml could not be found

### ISSUE THREAD

**Issue by onknows** [drhelius/terraform-azure-openshift#1]
This playbook does not exist. Does it matter that it didn't run?

https://github.com/onknows/terraform-azure-openshift/blob/eec212b3baa0d1f410599319c99d2281ada11b8b/scripts/install.sh#L45

**Comment by onknows** [comment]
This needs to be changed to playbooks/byo/config.yml

**Comment by drhelius** [comment]
This code is old, a lot of things have changed in OpenShift since.

All the issues you have reported are due to changes in the way it has to be installed now. 

Sorry but I no longer have access to an Azure account in order to test it again, feel free to modify it yourself.

**Comment by onknows** [comment]
OK I will try that. Thanks. One last question: Is there another way to create a similar environment easily based on this reference architecture? Similar to this GitHub project?

**Comment by drhelius** [comment]
I've updated it to Openshift 3.9
