### ISSUE TITLE
terraform destroy

### ISSUE THREAD

**Issue by onknows** [drhelius/terraform-azure-openshift#4]
How can I destroy  the infrastructure? Is this possible? I expected `terraform destroy` to do that but that is not the case. 

Do I need to use the Azure web interface?

**Comment by drhelius** [comment]
You can use `terraform destroy` if you change to the `terraform` folder. You may need to provide the `bootstrap.tfvars` file.
```
cd terraform
terraform destroy -var-file=../bootstrap.tfvars
```
